Fix bug in trustStore configuration.
Previously, SSLContextBuilder.setTrustStore was called only if
--keystore was used. Now it works with only --capath.

Example:

    % java com.semicomplete.ssl.Main --capath /tmp/certs --capath test.crt www.semicomplete.com

    www.semicomplete.com resolved to 4 addresses
    GOOD www.semicomplete.com:443[104.28.17.215]
    GOOD www.semicomplete.com:443[104.28.16.215]
    FAIL www.semicomplete.com:443[2400:cb00:2048:1:0:0:681c:11d7]
      Error: [class java.net.ConnectException] Network is unreachable
      No other diagnostic information available.
    FAIL www.semicomplete.com:443[2400:cb00:2048:1:0:0:681c:10d7]
      Error: [class java.net.ConnectException] Network is unreachable
      No other diagnostic information available.

Example with no trusted certs:

    % java com.semicomplete.ssl.Main --capath test.crt www.semicomplete.com
    www.semicomplete.com resolved to 4 addresses
    FAIL www.semicomplete.com:443[104.28.16.215]
     * Failure during SSL/TLS handshake
      Certificate Diagnostic
      Summary: My keystore has 1 trusted certificates, but none of them allow this server to be trusted.

      Server presented me with a chain of 3 certs.
      subject: CN=sni110717.cloudflaressl.com, OU=PositiveSSL Multi-Domain, OU=Domain Control Validated
      subject: CN=COMODO ECC Domain Validation Secure Server CA 2, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
      subject: CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
    FAIL www.semicomplete.com:443[104.28.17.215]
     * Failure during SSL/TLS handshake
      Certificate Diagnostic
      Summary: My keystore has 1 trusted certificates, but none of them allow this server to be trusted.

      Server presented me with a chain of 3 certs.
      subject: CN=sni110717.cloudflaressl.com, OU=PositiveSSL Multi-Domain, OU=Domain Control Validated
      subject: CN=COMODO ECC Domain Validation Secure Server CA 2, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
      subject: CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
    FAIL www.semicomplete.com:443[2400:cb00:2048:1:0:0:681c:10d7]
      Error: [class java.net.ConnectException] Network is unreachable
      No other diagnostic information available.
    FAIL www.semicomplete.com:443[2400:cb00:2048:1:0:0:681c:11d7]
      Error: [class java.net.ConnectException] Network is unreachable
      No other diagnostic information available.